function solar(a, target) {
    document.getElementById(a).style.display = 'block'

    if(target == "sun_info"){
    document.getElementById(target).style.display = 'block'
    document.getElementById('mercury_info').style.display = 'none'
    document.getElementById('venus_info').style.display = 'none'
    document.getElementById('earth_info').style.display = 'none'
    document.getElementById('mars_info').style.display = 'none'
    document.getElementById('jupiter_info').style.display = 'none'
    document.getElementById('saturn_info').style.display = 'none'
    document.getElementById('uranus_info').style.display = 'none'
    document.getElementById('neptune_info').style.display = 'none'
  }else if(target == "mercury_info"){
    document.getElementById(target).style.display = 'block'
    document.getElementById('sun_info').style.display = 'none'
    document.getElementById('venus_info').style.display = 'none'
    document.getElementById('earth_info').style.display = 'none'
    document.getElementById('mars_info').style.display = 'none'
    document.getElementById('jupiter_info').style.display = 'none'
    document.getElementById('saturn_info').style.display = 'none'
    document.getElementById('uranus_info').style.display = 'none'
    document.getElementById('neptune_info').style.display = 'none'
  }else if(target == "venus_info"){
    document.getElementById(target).style.display = 'block'
    document.getElementById('mercury_info').style.display = 'none'
    document.getElementById('sun_info').style.display = 'none'
    document.getElementById('earth_info').style.display = 'none'
    document.getElementById('mars_info').style.display = 'none'
    document.getElementById('jupiter_info').style.display = 'none'
    document.getElementById('saturn_info').style.display = 'none'
    document.getElementById('uranus_info').style.display = 'none'
    document.getElementById('neptune_info').style.display = 'none'
  }else if(target == "earth_info"){
    document.getElementById(target).style.display = 'block'
    document.getElementById('mercury_info').style.display = 'none'
    document.getElementById('venus_info').style.display = 'none'
    document.getElementById('sun_info').style.display = 'none'
    document.getElementById('mars_info').style.display = 'none'
    document.getElementById('jupiter_info').style.display = 'none'
    document.getElementById('saturn_info').style.display = 'none'
    document.getElementById('uranus_info').style.display = 'none'
    document.getElementById('neptune_info').style.display = 'none'
  }else if(target == "mars_info"){
    document.getElementById(target).style.display = 'block'
    document.getElementById('mercury_info').style.display = 'none'
    document.getElementById('venus_info').style.display = 'none'
    document.getElementById('sun_info').style.display = 'none'
    document.getElementById('earth_info').style.display = 'none'
    document.getElementById('jupiter_info').style.display = 'none'
    document.getElementById('saturn_info').style.display = 'none'
    document.getElementById('uranus_info').style.display = 'none'
    document.getElementById('neptune_info').style.display = 'none'
  }else if(target == "jupiter_info"){
    document.getElementById(target).style.display = 'block'
    document.getElementById('sun_info').style.display = 'none'
    document.getElementById('mercury_info').style.display = 'none'
    document.getElementById('venus_info').style.display = 'none'
    document.getElementById('mars_info').style.display = 'none'
    document.getElementById('earth_info').style.display = 'none'
    document.getElementById('saturn_info').style.display = 'none'
    document.getElementById('uranus_info').style.display = 'none'
    document.getElementById('neptune_info').style.display = 'none'
  }else if(target == "saturn_info"){
    document.getElementById(target).style.display = 'block'
    document.getElementById('sun_info').style.display = 'none'
    document.getElementById('mercury_info').style.display = 'none'
    document.getElementById('venus_info').style.display = 'none'
    document.getElementById('mars_info').style.display = 'none'
    document.getElementById('earth_info').style.display = 'none'
    document.getElementById('jupiter_info').style.display = 'none'
    document.getElementById('uranus_info').style.display = 'none'
    document.getElementById('neptune_info').style.display = 'none'
  }else if(target == "uranus_info"){
    document.getElementById(target).style.display = 'block'
    document.getElementById('sun_info').style.display = 'none'
    document.getElementById('mercury_info').style.display = 'none'
    document.getElementById('venus_info').style.display = 'none'
    document.getElementById('mars_info').style.display = 'none'
    document.getElementById('earth_info').style.display = 'none'
    document.getElementById('jupiter_info').style.display = 'none'
    document.getElementById('saturn_info').style.display = 'none'
    document.getElementById('neptune_info').style.display = 'none'
  }else if(target == "neptune_info"){
    document.getElementById(target).style.display = 'block'
    document.getElementById('sun_info').style.display = 'none'
    document.getElementById('mercury_info').style.display = 'none'
    document.getElementById('venus_info').style.display = 'none'
    document.getElementById('mars_info').style.display = 'none'
    document.getElementById('earth_info').style.display = 'none'
    document.getElementById('jupiter_info').style.display = 'none'
    document.getElementById('saturn_info').style.display = 'none'
    document.getElementById('uranus_info').style.display = 'none'
  }
}
